name: MagicLoot3
version: '${project.version}'
author: mrCookieSlime
contributors: [OoWJZZoO]
main: com.github.oowjzzoo.magicloot3.MagicLoot3
api-version: '1.21'
softdepend: [Slimefun]

website: https://github.com/OoWJZZoO/MagicLoot3

commands:
  magicloot:
    description: MagicLoot3 commands
    usage: /magicloot <version|debug|reload|generate <name>|language <zh|en>>

permissions:
  magicloot3.admin:
    description: Allows admin commands (debug, reload, generate)
    default: op
